---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
useCache: true
useGitignore: true
dictionaryDefinitions:
  - name: hpmor
    path: cspell-words.txt
dictionaries:
  - hpmor
language: de-DE,en-US
ignorePaths:
  - '/.vscode/'
  - 'cspell-words.txt'
  - 'cspell.config.yaml'
  - '/LICENSE'
  - '.gitignore'
  - 'Dockerfile'
  - 'GNUmakefile'
ignoreWords:
  - erstmal
languageSettings:
  - languageId: latex
    dictionaries:
      - hpmor
      - latex
    ignoreRegExpList:
      - '(^| )%.*'
  - languageId: python
    allowCompoundWords: true
    dictionaries:
      - python
      - wordsEn
      - wordsEnUS
