name: Make PDF layout test

on:
  workflow_dispatch:
#  push:
#    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Print start date
        run: date +%Y-%m-%d_%H:%M

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 1 # 0 if you want to push to repo

      - name: Python set up
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
          # cache: "pip"

      - name: Test ls before
        run: |
          pwd
          ls -al

      - name: Speed up apt-get steps
        uses: abbbi/github-actions-tune@v1

      - name: Install requirements
        run: |
          sudo apt-get update > /dev/null
          sh scripts/install_requirements_pdf.sh > /dev/null

      # unfortunately not working
      # - name: Cache packages
      #   uses: awalsh128/cache-apt-pkgs-action@latest
      #   with:
      #     packages: texlive-xetex texlive-lang-german latexmk
      #     version: 1.0
      #     execute_install_scripts: true

      - name: Print versions
        run: |
          cat /etc/os-release
          xelatex -v
          latexmk -v
          # pandoc -v
          python3 --version

      - name: Make PDF
        #      run: sh scripts/make_pdf.sh > /dev/null
        run: latexmk layout/test -f

      # - name: Publish log to release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     tag_name: WorkInProgress
      #     prerelease: true
      #     files: |
      #       ./test.log

      - name: Print end date
        run: date +%Y-%m-%d_%H:%M
