---
name: Make PDF all serial
# includes apt update

on:
  workflow_dispatch:

jobs:
  make:
    permissions:
      contents: write
    runs-on: ubuntu-26.04
    steps:

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 1  # latest only

      - name: Cache LaTeX files
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
        with:
          path: |
            chapters/*.aux
            hpmor*.aux
            hpmor*.fdb_latexmk
            hpmor*.fls
            hpmor*.out
            hpmor*.pdf
            hpmor*.toc
            hpmor*.xdv
          key: latex-build-files

      - name: Speed up apt-get steps
        uses: abbbi/github-actions-tune@81fb919e588c20b7ab52b2cac097d2efd765c714  # v1

      - name: Install PDF requirements
        run: |
          sudo apt-get update > /dev/null
          sh scripts/install_requirements_pdf.sh > /dev/null

      - name: Print versions
        run: |
          cat /etc/os-release
          xelatex -v
          latexmk -v
          # pandoc -v
          python3 --version

      - name: Make PDFs
        run: |
          latexmk hpmor-1 hpmor-2 hpmor-3 hpmor-4 hpmor-5 hpmor-6 hpmor > /dev/null

      - name: Publish PDF to release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64  # v3.0.3
        with:
          tag_name: WorkInProgress
          prerelease: false
          files: |
            hpmor*.pdf

      - name: Upload logs as artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: "hpmor.log"
          path: "hpmor*.log"
